---
- name: Test vars
  hosts: ansible-1
  tasks:
   - name: copy file
     copy: src=/etc/ansible/facts.d/front1.fact dest=/etc/ansible/facts.d/front1.fact
   - name: display the login variable
     debug: var=login
