---
- name: Test vars
  hosts: ansible-1
  become: true
  tasks:
    - name: "latest Ubuntu"
      apt: name=* state=latest
      when: ansible_os_family == 'Ubuntu'

    - name: "latest CentOS"
      yum: name=* state=latest
      when:
        - ansible_distribution == 'CentOS'
        - ansible_distribution_major_version >="7"

    - name: display_uptime
      shell: uptime
      register: value_uptime
      when:
        - display_uptime is defined

    - debug: msg="{{value_uptime.stdout}}"
      when:
        - display_uptime is defined
