- name: Install httpd
  yum: name=httpd
- name: Make sure a service is running
  systemd: state=started name=httpd
- name: enable service httpd and ensure it is not masked
  systemd:
    name: httpd
    enabled: yes
    masked: no
